- name: Update pip via easy_install
  become: yes
  shell: easy_install --upgrade pip

- name: Install python packages for El Capitan
  pip: name={{ item }} state=latest extra_args="--ignore-installed six"
  become: yes
  with_items:
    - awscli
    - pylint
  when: is_el_capitan

- name: Install python packages
  pip: name={{ item }} state=latest
  become: yes
  with_items:
    - awscli
    - pylint
    - ipdb
  when: not is_el_capitan

- name: Install python packages
  pip: name={{ item }} state=latest
  become: yes
  with_items:
    - boto
    - flake8
    - ipython
    - virtualenv
