- name: Update pip via easy_install
  sudo: yes
  shell: easy_install --upgrade pip

- set_fact:
    el_capitan: true
  when: ansible_distribution == "MacOSX" and ansible_distribution_version == "10.11.1"

- name: Install python packages for El Capitan
  pip: name={{ item }} state=latest extra_args="--ignore-installed six"
  sudo: yes
  with_items:
    - awscli
    - pylint
  when: el_capitan is defined and el_capitan == true

- name: Install python packages
  pip: name={{ item }} state=latest
  sudo: yes
  with_items:
    - awscli
    - pylint
    - ipdb
  when: el_capitan is undefined

- name: Install python packages
  pip: name={{ item }} state=latest
  sudo: yes
  with_items:
    - boto
    - flake8
    - ipython
    - virtualenv
